version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./:/app
      - node_modules:/app/node_modules/
    depends_on:
      - server-database
    networks:
      app-network:
    environment:
      - DATABASE_URL=mongodb://server-database:27017/ufood
      - PORT=8081
    restart: always
  server-database:
    image: mongo
    volumes:
      - dbdata:/data/db
    networks:
      app-network:

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
